# -*- coding: utf-8 -*-
"""webscraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Fa2NDvoMZsKVwGvA9oKEFjbeAHAyKRS

# instaling beautifulsoup4
"""

!pip install beautifulsoup4

!pip install lxml

!pip install requests

from bs4 import BeautifulSoup
import requests
import requests
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'From': 'abdeljalil.betrouni@g.enp.edu.dz'  # This is another valid field
}

web_html= requests.get('https://bigfuture.collegeboard.org/scholarship-search', headers=headers).text

soup=BeautifulSoup(web_html, 'lxml')
offers=soup.find_all('p')